- job:
    name: trigger-ci-job-configs
    project-type: freestyle
    defaults: global
    properties:
        - authorization:
            anonymous:
                - job-discover
            linaro:
                - job-read
                - job-extended-read
        - build-discarder:
            days-to-keep: 30
            num-to-keep: 200
    disabled: false
    node: master
    display-name: 'CI job configs deployment'
    triggers:
        - pollscm: 'H/5 * * * *'
    wrappers:
        - timestamps
        - credentials-binding:
            - text:
                credential-id: JJB_USER
                variable: JJB_USER
        - credentials-binding:
            - text:
                credential-id: JJB_PASSWORD
                variable: JJB_PASSWORD
        - credentials-binding:
            - text:
                credential-id: LAVA_USER
                variable: LAVA_USER
        - credentials-binding:
            - text:
                credential-id: LAVA_TOKEN
                variable: LAVA_TOKEN
    builders:
        - shell: |
            #!/bin/bash

            set -e

            rm -rf ${WORKSPACE}/*

            git clone https://github.com/roxell/kernelci-configs.git
            cd kernelci-configs

            export GIT_PREVIOUS_COMMIT=$(git rev-parse HEAD~1)
            export GIT_COMMIT=$(git rev-parse HEAD)

            jenkins-jobs --version
            python run-jjb.py
    publishers:
        - email:
            recipients: 'anders.roxell@linaro.org'
